import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { UsersService } from '../users.service';
import { IUsers } from '../iusers';

import { BaseDetailsComponent, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

@Component({
  selector: 'app-users-details',
  templateUrl: './users-details.component.html',
  styleUrls: ['./users-details.component.scss'],
})
export class UsersDetailsComponent extends BaseDetailsComponent<IUsers> implements OnInit {
  title = 'Users';
  parentUrl = 'users';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public usersService: UsersService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, pickerDialogService, usersService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Users';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      displayName: [''],
      email: ['', Validators.required],
      isActive: [false, Validators.required],
      isEmailConfirmed: [{ value: false, disabled: true }, Validators.required],
      username: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'username',
        label: 'username',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'isEmailConfirmed',
        label: 'is Email Confirmed',
        isRequired: true,
        isAutoGenerated: false,
        type: 'boolean',
      },
      {
        name: 'isActive',
        label: 'is Active',
        isRequired: true,
        isAutoGenerated: false,
        type: 'boolean',
      },
      {
        name: 'email',
        label: 'email',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'displayName',
        label: 'display Name',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
    ];
  }

  onItemFetched(item: IUsers) {
    this.item = item;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'username',
            value: undefined,
            referencedkey: 'username',
          },
        ],
        isParent: true,
        table: 'person',
        type: 'OneToMany',
        label: 'persons',
      },
      {
        column: [
          {
            key: 'usersUsername',
            value: undefined,
            referencedkey: 'username',
          },
        ],
        isParent: true,
        table: 'userspermission',
        type: 'OneToMany',
        label: 'Userpermissions',
      },
      {
        column: [
          {
            key: 'usersUsername',
            value: undefined,
            referencedkey: 'username',
          },
        ],
        isParent: true,
        table: 'usersrole',
        type: 'OneToMany',
        label: 'Userroles',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let users = this.itemForm.getRawValue();
    super.onSubmit(users);
  }
}
