import { Component, OnInit, Inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialogRef, MatDialog, MAT_DIALOG_DATA } from '@angular/material/dialog';

import { CaseHistoryService } from '../case-history.service';
import { ICaseHistory } from '../icase-history';
import { BaseNewComponent, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { CasesService } from 'src/app/entities/cases/cases.service';

@Component({
  selector: 'app-case-history-new',
  templateUrl: './case-history-new.component.html',
  styleUrls: ['./case-history-new.component.scss'],
})
export class CaseHistoryNewComponent extends BaseNewComponent<ICaseHistory> implements OnInit {
  title: string = 'New CaseHistory';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public dialogRef: MatDialogRef<CaseHistoryNewComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public pickerDialogService: PickerDialogService,
    public caseHistoryService: CaseHistoryService,
    public errorService: ErrorService,
    public casesService: CasesService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, dialogRef, data, pickerDialogService, caseHistoryService, errorService);
  }

  ngOnInit() {
    this.entityName = 'CaseHistory';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.checkPassedData();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      caseHistoryId: ['', Validators.required],
      message: [''],
      timestamp: ['12:00 AM', Validators.required],
      caseId: ['', Validators.required],
      casesDescriptiveField: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'timestamp',
        label: 'timestamp',
        isRequired: true,
        isAutoGenerated: false,
        type: 'time',
      },
      {
        name: 'message',
        label: 'message',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'caseHistoryId',
        label: 'case History Id',
        isRequired: true,
        isAutoGenerated: false,
        type: 'number',
      },
    ];
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'caseId',
            value: undefined,
            referencedkey: 'caseId',
          },
        ],
        isParent: false,
        table: 'cases',
        type: 'ManyToOne',
        service: this.casesService,
        label: 'cases',
        descriptiveField: 'casesDescriptiveField',
        referencedDescriptiveField: 'caseId',
      },
    ];
    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let caseHistory = this.itemForm.getRawValue();
    caseHistory.timestamp = this.dataService.getFormattedTime(caseHistory.timestamp, true);
    super.onSubmit(caseHistory);
  }
}
