import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { PersonService } from '../person.service';
import { IPerson } from '../iperson';

import { BaseDetailsComponent, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { UsersService } from 'src/app/admin/user-management/users/users.service';

@Component({
  selector: 'app-person-details',
  templateUrl: './person-details.component.html',
  styleUrls: ['./person-details.component.scss'],
})
export class PersonDetailsComponent extends BaseDetailsComponent<IPerson> implements OnInit {
  title = 'Person';
  parentUrl = 'person';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public personService: PersonService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public usersService: UsersService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, pickerDialogService, personService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Person';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      birthDate: [''],
      comments: [''],
      givenName: [''],
      homePhone: [''],
      personId: ['', Validators.required],
      surname: [''],
      username: [''],
      usersDescriptiveField: [''],
    });

    this.fields = [
      {
        name: 'surname',
        label: 'surname',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'personId',
        label: 'person Id',
        isRequired: true,
        isAutoGenerated: false,
        type: 'number',
      },
      {
        name: 'homePhone',
        label: 'home Phone',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'givenName',
        label: 'given Name',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'comments',
        label: 'comments',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'birthDate',
        label: 'birth Date',
        isRequired: false,
        isAutoGenerated: false,
        type: 'date',
      },
    ];
  }

  onItemFetched(item: IPerson) {
    this.item = item;
    this.itemForm.patchValue(item);
    this.itemForm.get('birthDate').setValue(item.birthDate ? new Date(item.birthDate) : null);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'personId',
            value: undefined,
            referencedkey: 'personId',
          },
        ],
        isParent: true,
        table: 'personCase',
        type: 'OneToMany',
        label: 'personCases',
      },
      {
        column: [
          {
            key: 'username',
            value: undefined,
            referencedkey: 'username',
          },
        ],
        isParent: false,
        table: 'users',
        type: 'ManyToOne',
        label: 'users',
        service: this.usersService,
        descriptiveField: 'usersDescriptiveField',
        referencedDescriptiveField: 'username',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let person = this.itemForm.getRawValue();
    super.onSubmit(person);
  }
}
