import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { TaskService } from '../task.service';
import { ITask } from '../itask';

import { BaseDetailsComponent, PickerDialogService } from 'src/app/common/shared';
import { ErrorService } from 'src/app/core/services/error.service';
import { GlobalPermissionService } from 'src/app/core/services/global-permission.service';

import { CasesService } from 'src/app/entities/cases/cases.service';

@Component({
  selector: 'app-task-details',
  templateUrl: './task-details.component.html',
  styleUrls: ['./task-details.component.scss'],
})
export class TaskDetailsComponent extends BaseDetailsComponent<ITask> implements OnInit {
  title = 'Task';
  parentUrl = 'task';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public taskService: TaskService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public casesService: CasesService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, pickerDialogService, taskService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Task';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      message: [''],
      status: [''],
      taskId: ['', Validators.required],
      type: [''],
      username: [''],
      caseId: [''],
      casesDescriptiveField: [''],
    });

    this.fields = [
      {
        name: 'username',
        label: 'username',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'type',
        label: 'type',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'taskId',
        label: 'task Id',
        isRequired: true,
        isAutoGenerated: false,
        type: 'number',
      },
      {
        name: 'status',
        label: 'status',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'message',
        label: 'message',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
    ];
  }

  onItemFetched(item: ITask) {
    this.item = item;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'caseId',
            value: undefined,
            referencedkey: 'caseId',
          },
        ],
        isParent: false,
        table: 'cases',
        type: 'ManyToOne',
        label: 'cases',
        service: this.casesService,
        descriptiveField: 'casesDescriptiveField',
        referencedDescriptiveField: 'caseId',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let task = this.itemForm.getRawValue();
    super.onSubmit(task);
  }
}
